export const pathLinks = {
    home: '/home',
    redaction: '/redaction/:id',
    error: '/error',
    login: '/login',
    reg: '/reg',
    addEmpl: '/addEmpl',
    allAboutUser: '/user/:id/all',
};

export const USERS_ON_PAGE = 6;
export const DATE_MASK = 'dd/mm/yyyy';

export const actionType = {
    CHANGE_ACTIVE_POPUP: 'CHANGE_ACTIVE_POPUP',
    LOAD_DATA: 'LOAD_DATA',
    LOAD_DATA_SUCCEEDED: 'LOAD_DATA_SUCCEEDED',
    LOAD_DATA_FAILED: 'LOAD_DATA_FAILED',
    PUSHED_DATA: 'PUSHED_DATA',
    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE',
    SING_IN_USER: 'SING_IN_USER',
    SING_UP_USER: 'SING_UP_USER',
    SING_IN_USER_SUCCESSED: 'SING_IN_USER_SUCCESSED',
    SING_UP_USER_SUCCESSED: 'SING_UP_USER_SUCCESSED',
    SING_IN_USER_FAILED: 'SING_IN_USER_FAILED',
    SING_UP_USER_FAILED: 'SING_UP_USER_FAILED',
    CREATE_USER_SUCCESSED: 'CREATE_USER_SUCCESSED',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
    CREATE_USER: 'CREATE_USER',
    DELETE_USER: 'DELETE_USER',
    FIND_USER: 'FIND_USER',
    FIND_USER_SUCCEEDED: 'FIND_USER_SUCCEEDED',
    CLEAR_ERROR: 'CLEAR_ERROR',
    LOAD_ALL_ABOUT_USER_SUCCESSED: 'LOAD_ALL_ABOUT_USER_SUCCESSED',
    LOAD_ALL_ABOUT_USER: 'LOAD_ALL_ABOUT_USER',
};
